### ISSUE TITLE
Can I use this for TF RNN Language Model?

### ISSUE THREAD

**Issue by dixiematt8** [maxim5/hyper-engine#1]
Can you please add one example for DNN hyper-parameter tuning?

**Comment by maxim5** [comment]
Hi @dixiematt8,

Sorry for the delay, I finally got my hands on this. I've added a bunch of [examples](https://github.com/maxim5/hyper-engine/tree/master/hyperengine/examples) to show how it works, in particular, there are few examples of RNN and NLP models. Hope you'll find it useful and thanks for your interest.

**Comment by dixiematt8** [comment]
Thanks
