### ISSUE TITLE
Selecting the method

### ISSUE THREAD

**Issue by NRT23** [maxim5/hyper-engine#14]
Hi! Thank you for making a great library.

I was wondering how can I specify different methods (utilities) when optimizing?
It seems that "UpperConfidenceBound" is the default option and I tried to specify something like strategy_params = {
    'utility':  'ExpectedImprovement'
}

and some other attempts but without much success. And in the source code, I have not found how I can do this. Could you kindly provide some explanation on this?

Thank you very much in advance!

**Comment by maxim5** [comment]
Hi @NRT23 

Try the following:
```
strategy_params = {
   'utility_gen': 'ei',
    ...
}
```

I know it's a bit cryptic, I should probably detail everything in the doc.
Available options are listed here: https://github.com/maxim5/hyper-engine/blob/master/hyperengine/bayesian/strategy.py#L24

Also note that utilities can have parameters of their own.

**Comment by NRT23** [comment]
@maxim5 Hi!

Thanks, it works! The examples you have are very good, there is just a little lack of documentation. However, what I really like is the this is the only Bayesian optimization library (at least what I have found) which you can use directly with Tensroflow (not Keras). And it is easy to use except specifying the method :) Thanks a lot and keep up good work!
