### ISSUE TITLE
Missing usage examples

### ISSUE THREAD

**Issue by skeggse** [maxim5/hyper-engine#2]
I found this project from your [post](https://stackoverflow.com/a/46261634) on stackoverflow. I'd like to experiment with it, but I'm unclear on how to use it - there isn't any obvious documentation describing the use of hyper-engine.

The README says hyper-engine provides a tensorflow binding. Depending on what that binding entails, it may or may not accommodate my use-case.

**Comment by maxim5** [comment]
@skeggse You're right, code examples are definitely missing. I intend to simplify the API even more and then add examples for various problems and networks, such as CNN, RNN, autoencoders, etc. Will get to it as soon as I have some free time.

What is your use case?

**Comment by skeggse** [comment]
I need to perform nested cross-validation for hyperparameter/model selection and model evaluation, and would like to minimize the work needed to run the inner cross-validation with hyper-engine. Depending on how the tensorflow bindings are implemented, I may not be able to leverage the cluster I have access to appropriately, so my use-case is likely just a module I use to early stop training based on learning curve prediction, and to schedule the right jobs with appropriate hyperparameters outside of an actual script running tensorflow.

Is there anything I can help with as far as implementation goes? I just need a bit of internal documentation to understand what the various parts of hyper-engine are and how they fit together. I'd love to contribute!

**Comment by maxim5** [comment]
Hi @skeggse Thanks for your interest. I've reworked API and uploaded a [bunch of examples](https://github.com/maxim5/hyper-engine/blob/master/hyperengine/examples) this weekend, and plan to add more. Please take a look to get a sense how it works in theory. I'm ready to discuss the architecture.

**Comment by skeggse** [comment]
Amazing, many thanks! I'm taking a look at the examples now. I'll get back to you soon on architecture ideas.

**Comment by skeggse** [comment]
I'm also closing this issue as it pertains specifically to usage examples, and the new examples are super helpful.
